# -*- coding: utf-8 -*-
"""Strofig_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1O29Fc9JPYEpy56qlIZQvR7ImIO0dmP
"""

import streamlit as st
import pandas as pd
import numpy as np

# --- LÓGICA DE INTEROLACION ---
def interpolar_bilineal(x, y, x1, x2, y1, y2, Q11, Q21, Q12, Q22):
    if (x2 - x1) == 0 or (y2 - y1) == 0:
        return np.nan
    return (Q11 * (x2 - x) * (y2 - y) + Q21 * (x - x1) * (y2 - y) +
            Q12 * (x2 - x) * (y - y1) + Q22 * (x - x1) * (y - y1)) / ((x2 - x1) * (y2 - y1))

def buscar_gamma_interpolado(h, v, h_angles, v_angles, gamma_matrix):
    h_angles_arr, v_angles_arr = np.array(h_angles), np.array(v_angles)

    def vecinos(valores, objetivo):
        menores = valores[valores < objetivo]
        mayores = valores[valores > objetivo]
        if len(menores) == 0 or len(mayores) == 0: return None
        return menores.max().item(), mayores.min().item()

    def _perform_interpolation(target_h, target_v, h_local, v_local, mat_local):
        h1h2, v1v2 = vecinos(h_local, target_h), vecinos(v_local, target_v)
        if h1h2 and v1v2:
            h1, h2 = h1h2
            v1, v2 = v1v2
            i1, i2 = np.where(v_local == v1)[0][0].item(), np.where(v_local == v2)[0][0].item()
            j1, j2 = np.where(h_local == h1)[0][0].item(), np.where(h_local == h2)[0][0].item()
            Q = [mat_local[i1, j1], mat_local[i2, j1], mat_local[i1, j2], mat_local[i2, j2]]
            if not any(np.isnan(Q)):
                return interpolar_bilineal(target_h, target_v, h1, h2, v1, v2, *Q)
        return None

    for a, b in [(h, v), (v, h)]:
        match_h = np.where(np.isclose(h_angles_arr, a))[0]
        match_v = np.where(np.isclose(v_angles_arr, b))[0]
        if len(match_h) > 0 and len(match_v) > 0:
            val = gamma_matrix[match_v[0], match_h[0]]
            if not np.isnan(val): return val

    res = _perform_interpolation(h, v, h_angles_arr, v_angles_arr, gamma_matrix)
    return res if res is not None else _perform_interpolation(v, h, h_angles_arr, v_angles_arr, gamma_matrix)

# --- GUI EN STREAMLIT  ---
st.set_page_config(page_title="Módulo Rigidez de Figura", page_icon="🛰️")
st.title("Rigidez de Figura")

with st.sidebar:
    st.header("Configuración de Red")
    l = st.number_input("l (Líneas totales)", value=0, step=1)
    lp = st.number_input("l' (Líneas Visadas 2-dir)", value=0, step=1)
    s = st.number_input("s (Estaciones totales)", value=0, step=1)
    sp = st.number_input("s' (Est. Ocupadas)", value=0, step=1)

    # Botón para limpiar datos
    if st.button("Limpiar lista de ángulos"):
        st.session_state.pares = []
        st.rerun()

# Calculo de condiciones de lado
D = 2 * l - 2
C = (lp - sp + 1) + (l - 2 * s + 3)
F = (D - C) / D if D > 0 else 0

st.info(f"**Factor F:** {F:.4f} | **D:** {D} | **C:** {C}")

# Manejo de la lista
if 'pares' not in st.session_state:
    st.session_state.pares = []

st.subheader("Entrada de Ángulos")
col1, col2 = st.columns(2)
alfa = col1.number_input("Alfa (α)", value=0, step=1, format="%d", min_value=0)
beta = col2.number_input("Beta (β)", value=0, step=1, format="%d", min_value=0)

if st.button("Añadir Par"):
    if alfa > 0 and beta > 0:
        st.session_state.pares.append({'α': alfa, 'β': beta})
        st.toast("Par añadido correctamente")
    else:
        st.warning("Ingrese ángulos mayores a 0")

# Mostrar lista actual
if st.session_state.pares:
    st.write("### Pares en la cadena:")
    st.dataframe(pd.DataFrame(st.session_state.pares), use_container_width=True)

# Cálculo final
if st.button("Calcular Rigidez Total"):
    if not st.session_state.pares:
        st.error("No hay ángulos registrados en la cadena.")
    else:
        try:
            # Carga de tabla
            df_table = pd.read_csv("gamma_table.csv", sep=";", index_col=0)
            h_angles = df_table.columns.astype(float)
            v_angles = df_table.index.astype(float)
            matrix = df_table.to_numpy()

            resultados, suma_gamma = [], 0

            # Primero calculamos la sumatoria para tener el R_Total disponible
            for p in st.session_state.pares:
                val = buscar_gamma_interpolado(p['α'], p['β'], h_angles, v_angles, matrix)
                suma_gamma += val if val is not None else 0

            r_total = round(F * suma_gamma, 2)

            # Ahora armamos la lista de resultados con TODA la información técnica
            for p in st.session_state.pares:
                val = buscar_gamma_interpolado(p['α'], p['β'], h_angles, v_angles, matrix)
                resultados.append({
                    'l': l, "l'": lp, 's': s, "s'": sp,    # Entradas originales
                    'D': D, 'C': C, 'Factor_F': round(F, 4), # Valores calculados
                    'Alfa': p['α'],
                    'Beta': p['β'],
                    'Gamma': round(val, 4) if val is not None else "Error",
                    'Suma_Gamma': round(suma_gamma, 4),
                    'R_Total': r_total
                })

            # Mostrar éxito en la interfaz
            st.success(f"### Análisis Completado: Rigidez = {r_total}")

            # Crear DataFrame y mostrarlo
            df_res = pd.DataFrame(resultados)

            # En la web mostramos una versión simplificada para que no se vea tan cargada
            st.write("### Vista previa del reporte:")
            st.dataframe(df_res[['Alfa', 'Beta', 'Gamma', 'Factor_F', 'R_Total']], use_container_width=True)

            # El CSV para descarga sí llevará TODAS las columnas para validación manual
            csv = df_res.to_csv(index=False, sep=';', encoding='utf-8-sig').encode('utf-8-sig')

            st.download_button(
                label="📥 Descargar Archivo (CSV)",
                data=csv,
                file_name="Reporte_Rigidez.csv",
                mime="text/csv",
            )

        except FileNotFoundError:
            st.error("No se encontró 'gamma_table.csv'. Verifica que el archivo esté en tu repositorio de GitHub.")
